# Generated by Django 5.0.4 on 2024-04-22 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(max_length=1000, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_user', models.DateTimeField(auto_now=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('duration_tot', models.IntegerField()),
                ('num_songs', models.IntegerField()),
                ('photo', models.TextField(max_length=500)),
                ('desc', models.TextField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Like_playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.gender')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.playlist')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='musicfy.rol'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('photo', models.TextField(max_length=500)),
                ('url_song', models.TextField(max_length=500)),
                ('duration', models.FloatField(default=0)),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.playlist')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.song')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.song')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_send_requeest', to=settings.AUTH_USER_MODEL)),
                ('id_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recive_requeest', to=settings.AUTH_USER_MODEL)),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.status')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('id_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_send_msgt', to=settings.AUTH_USER_MODEL)),
                ('id_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recibe_msg', to=settings.AUTH_USER_MODEL)),
                ('id_type_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicfy.type_message')),
            ],
        ),
    ]
