# Generated by Django 5.0.4 on 2024-05-08 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.TextField(max_length=500, null=True)),
                ('password', models.TextField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('create_user', models.DateTimeField(auto_now=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('id_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='musicfy.rol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
