# Generated by Django 5.0.4 on 2024-04-18 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicfy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='paswword',
            new_name='pasword',
        ),
    ]
