# Generated by Django 5.0.4 on 2024-05-08 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlist', '0001_initial'),
        ('musicfy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_send_requeest', to='musicfy.user')),
                ('id_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicfy.status')),
                ('id_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recive_requeest', to='musicfy.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like_playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Playlist.playlist')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicfy.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Playlist.playlist')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicfy.user')),
            ],
        ),
    ]
