# Generated by Django 5.0.4 on 2024-04-23 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlist', '0002_playlist_gender_playlist_songs'),
        ('musicfy', '0002_rol_status_user_id_rol_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Playlist.playlist')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Playlist.playlist')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
