# Generated by Django 5.0.4 on 2024-04-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicfy', '0002_rename_paswword_user_pasword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pasword',
            new_name='password',
        ),
    ]
