# Generated by Django 5.0.4 on 2024-04-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicfy', '0003_like_playlist_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
