# Generated by Django 5.0.4 on 2024-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('photo', models.TextField(max_length=500)),
                ('url_song', models.TextField(max_length=500)),
                ('duration', models.FloatField(default=0)),
            ],
        ),
    ]
