# Generated by Django 5.0.4 on 2024-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('duration_tot', models.IntegerField()),
                ('num_songs', models.IntegerField()),
                ('photo', models.TextField(max_length=500)),
                ('desc', models.TextField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
