# Generated by Django 5.0.4 on 2024-04-23 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlist', '0001_initial'),
        ('Song', '0002_gender_artist_song_song_gender_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Song.gender')),
                ('id_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Playlist.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Playlist.playlist')),
                ('id_song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Song.song')),
            ],
        ),
    ]
